

import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from 'next/font/google';
import Nav from '@/components/Nav';

// import { useEffect } from 'react';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // useEffect(() => {
  //   typeof document !== undefined
  //     ? require("bootstrap/dist/js/bootstrap")
  //     : null;
  // }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  )
}
